ballerina-platform/fhir-tools

README.md
native/health-cli/src/main/java/io/ballerina/health/cmd/HealthCmd.java
native/health-cli/src/main/java/io/ballerina/health/cmd/fhir/FhirSubCmd.java
native/health-cli/src/main/resources/ballerina-health.help
pom.xml

> fix: https://github.com/wso2-enterprise/open-healthcare/issues/1305
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

Add support for Ballerina v2201.7.0 Add proper error handling

---

README.md
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/BallerinaPackageGenTool.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/ToolConstants.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/config/PackageConfig.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/modelgen/ResourceContextGenerator.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/templategen/PackageTemplateGenerator.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/templategen/ResourceTemplateGenerator.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/utils/CommonUtil.java
native/health-cli/src/main/resources/tool-config.json

> Match the sources with the latest state of the Open Healthcare Integration repository's [codegen branch](https://github.com/wso2-enterprise/open-healthcare-integration/tree/codegen-tool-framework).
> Move all the Ballerina artifact generator tools to a single repository.

Rebasing oh-integration codegen branch

---

native/health-cli/src/main/java/io/ballerina/health/cmd/fhir/FhirSubCmd.java

> $Subject. 
> Related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1308

Fix preventing logs printing from the dependent libraries

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/BallerinaPackageGenTool.java
native/health-cli/src/main/java/io/ballerina/health/cmd/fhir/FhirSubCmd.java

Add several error handling scenarios and improvements

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/utils/CommonUtil.java

Remove hyphen in backbone datatype name generation

Remove hyphen in backbone datatype name generation

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/modelgen/ResourceContextGenerator.java

Fix issue with missing constraint import when BB elements present

---

native/health-cli/src/main/java/io/ballerina/health/cmd/core/utils/HealthCmdUtils.java
native/health-cli/src/main/java/io/ballerina/health/cmd/fhir/FhirSubCmd.java
native/health-cli/src/main/resources/ballerina-health.help

update Helptext, fix minor fixes in input path

---

ballerina/pom.xml
native/fhir-to-bal-lib/pom.xml
native/fhir-to-bal-template/pom.xml
native/health-cli/pom.xml
pom.xml

Rollback version to snapshot

---

native/health-cli/src/main/java/io/ballerina/health/cmd/fhir/FhirSubCmd.java
native/health-cli/src/main/resources/ballerina-health.help

Refine helptext.

---

ballerina/pom.xml
native/fhir-to-bal-lib/pom.xml
native/fhir-to-bal-template/pom.xml
native/health-cli/pom.xml
pom.xml

[1.0.0 release] Prepare for release

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/templategen/PackageTemplateGenerator.java

Add warning in package-gen tool when overriding already generated packages

---

README.md
native/fhir-to-bal-lib/pom.xml
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/config/PackageConfig.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/utils/CommonUtil.java
native/health-cli/pom.xml
native/health-cli/src/main/java/io/ballerina/health/cmd/HealthCmd.java
native/health-cli/src/main/java/io/ballerina/health/cmd/fhir/FhirSubCmd.java
native/health-cli/src/main/resources/ballerina-health.help

> fix:https://github.com/wso2-enterprise/open-healthcare/issues/1317

Simplify input path, normalize IG name, update default name derivation

---

native/health-cli/src/main/java/io/ballerina/health/cmd/fhir/FhirSubCmd.java
native/health-cli/src/main/resources/ballerina-health.help

> Fix help text issues reported in: https://github.com/wso2-enterprise/open-healthcare/issues/1317
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

Helptext improvements.

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/modelgen/ResourceContextGenerator.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/utils/VelocityUtil.java
native/fhir-to-bal-lib/src/main/resources/templates/fhir_resource.vm

Add fix to resolve Ballerina keyword conflicts

Add fix to resolve Ballerina keyword conflicts

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/BallerinaPackageGenTool.java
native/health-cli/src/main/java/io/ballerina/health/cmd/HealthCmd.java
native/health-cli/src/main/java/io/ballerina/health/cmd/core/utils/HealthCmdConstants.java
native/health-cli/src/main/java/io/ballerina/health/cmd/fhir/FhirSubCmd.java
native/health-cli/src/main/resources/ballerina-health.help

Changes requested in the demo

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/modelgen/ResourceContextGenerator.java

Add fix for slice element population

Add fix for slice element population

---

native/health-cli/src/main/resources/ballerina-health.help

fix: https://github.com/wso2-enterprise/open-healthcare/issues/1317

Help text fixes

---

native/health-cli/src/main/resources/ballerina-health.help

Minor readme changes

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/config/PackageConfig.java

fix formatting issues

---

ballerina/pom.xml
native/fhir-to-bal-lib/pom.xml
native/fhir-to-bal-template/pom.xml
native/health-cli/pom.xml
pom.xml

[Release v1.0.0] Prepare for next development cycle

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/model/Element.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/modelgen/ResourceContextGenerator.java
native/fhir-to-bal-lib/src/main/resources/templates/fhir_resource.vm

Add fix to generate datatype for splice elements.
With this fix, a separate datatype will be generated for each splice definition of a resource field.

Add fix to generate datatype for splice elements

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/model/Element.java
native/fhir-to-bal-lib/src/main/resources/templates/fhir_resource.vm

> fixing:https://github.com/wso2-enterprise/open-healthcare/issues/1348
> previous logic was checking if the min value is equal to 0 when deciding to add a constraint. This should be changed as min_value  > 0

Change constraint min to accept a range

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/ToolConstants.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/model/Element.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/model/ExtendedElement.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/model/ResourceTemplateContext.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/modelgen/ResourceContextGenerator.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/templategen/ResourceTemplateGenerator.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/utils/CommonUtil.java
native/fhir-to-bal-lib/src/main/resources/templates/fhir_resource.vm

Add Ballerina docs for sliced elements
Related Issue: https://github.com/wso2-enterprise/open-healthcare/issues/1349

Add Ballerina docs for sliced elements

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/model/Element.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/modelgen/ResourceContextGenerator.java
native/fhir-to-bal-lib/src/main/resources/templates/fhir_resource.vm

Add constraint imports for resources with constrained child elements

Add constraint imports for resources with constrained child elements

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/model/Element.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/model/ResourceTemplateContext.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/modelgen/ResourceContextGenerator.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/templategen/ResourceTemplateGenerator.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/utils/GeneratorUtils.java
native/fhir-to-bal-lib/src/main/resources/templates/fhir_resource.vm

Add datatype generation for differential elements
Related Issue: https://github.com/wso2-enterprise/open-healthcare/issues/1398

Add datatype generation for differential elements

---

native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/model/FHIRProfile.java
native/health-cli/src/main/java/io/ballerina/health/cmd/fhir/FhirSubCmd.java

Fixing the following:
https://github.com/wso2-enterprise/open-healthcare/issues/1441
https://github.com/wso2-enterprise/open-healthcare/issues/1442

Fix issues with output text and ig pkg name

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/modelgen/PackageContextGenerator.java
native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/BallerinaProjectTool.java
native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/config/BallerinaProjectToolConfig.java
native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/generator/BallerinaProjectGenerator.java
native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/generator/ServiceGenerator.java
native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/generator/TomlGenerator.java
native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/model/FHIRProfile.java
native/fhir-to-bal-template/src/main/resources/template/ballerinaToml.vm
native/fhir-to-bal-template/src/main/resources/template/packageMd.vm
native/health-cli/src/main/java/io/ballerina/health/cmd/fhir/FhirSubCmd.java
native/health-cli/src/main/java/io/ballerina/health/cmd/handler/TemplateGenHandler.java
native/health-cli/src/main/resources/ballerina-health.help
native/health-cli/src/main/resources/tool-config.json

* Make package name mandatory for package gen.
* Make dependent package mandatory for template gen.
* Rename --ig-package to --dependent-package
* Remove --dependency option and its initialization
* Update help text

Add multiple improvements

---

native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/generator/ServiceGenerator.java
native/fhir-to-bal-template/src/main/resources/template/balService.vm

Add fix for resource method incorrect return types
Related Issue: https://github.com/wso2-enterprise/open-healthcare/issues/1449

Add fix for resource method incorrect return types

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/model/Element.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/utils/GeneratorUtils.java

Change fixed valued fields from optional to required

Change fixed valued fields from optional to required

---

native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/BallerinaProjectTool.java
native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/model/FHIRProfile.java
native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/util/BallerinaProjectUtil.java
native/fhir-to-bal-template/src/main/resources/template/balService.vm

Fix Issues
- Remove special characters from resource profiles.
- Remove special characters from strings.
- Skip generating templates for resource Bundle, CodeSystem, DomainResource, OperationOutcome, Resource and ValueSet.

Fix Issues

---

ballerina/pom.xml
native/fhir-to-bal-lib/pom.xml
native/fhir-to-bal-template/pom.xml
native/health-cli/pom.xml
pom.xml

[Release v2.1.0] Prepare for release

[Release v2.1.0] Prepare for release

---

ballerina/pom.xml
native/fhir-to-bal-lib/pom.xml
native/fhir-to-bal-template/pom.xml
native/health-cli/pom.xml
pom.xml

Release health tool v2.1.0

---

.github/workflows/cd.yml
.github/workflows/ci.yml
pom.xml

Update the codegen tool framework version

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/model/ResourceTemplateContext.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/modelgen/ResourceContextGenerator.java
native/fhir-to-bal-lib/src/main/resources/templates/fhir_extended_datatypes.vm
native/fhir-to-bal-lib/src/main/resources/templates/fhir_resource.vm

Add fix for issues
- Remove special characters in datatype profile names
- Add fix for cardinality discrepancies in slicings against their original datatype definition
Related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1504

Add fix for issues

---

ballerina/pom.xml
native/fhir-to-bal-lib/pom.xml
native/fhir-to-bal-template/pom.xml
native/health-cli/pom.xml
pom.xml

[Release v2.1.1] Prepare for next dev cycle

[Release v2.1.1] Prepare for next dev cycle

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/ToolConstants.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/modelgen/ResourceContextGenerator.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/templategen/DatatypeTemplateGenerator.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/templategen/PackageTemplateGenerator.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/templategen/ResourceTemplateGenerator.java
native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/BallerinaProjectConstants.java
native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/generator/MetaGenerator.java
native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/generator/ServiceGenerator.java
native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/generator/TomlGenerator.java

Related Issue: https://github.com/wso2-enterprise/open-healthcare/issues/1506

Replace File.separator with "/" for cross-platform path handling

---

.github/workflows/cd.yml
.github/workflows/ci.yml
pom.xml

Update codegen tool framework version

---

README.md

Improve the Readme file

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/ToolConstants.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/config/BallerinaPackageGenToolConfig.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/config/PackageConfig.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/model/DataTypeProfile.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/model/Element.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/modelgen/ResourceContextGenerator.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/utils/GeneratorUtils.java
native/fhir-to-bal-lib/src/main/resources/templates/fhir_resource.vm
native/health-cli/src/main/java/io/ballerina/health/cmd/fhir/FhirSubCmd.java
native/health-cli/src/main/java/io/ballerina/health/cmd/handler/FhirPackageGenHandler.java
native/health-cli/src/main/resources/ballerina-health.help
native/health-cli/src/main/resources/tool-config.json

> fix: https://github.com/wso2-enterprise/open-healthcare/issues/1617

Fixed nested slices issue, add support to custom datatype prefix

---

native/cds-bal-template/src/main/java/org/wso2/healthcare/cds/codegen/ballerina/tool/generator/BallerinaCDSProjectGenerator.java
native/cds-bal-template/src/main/resources/template/implDecisionSystemConnection.vm

Fix bug for cds template generation

---

ballerina/pom.xml
native/cds-bal-template/pom.xml
native/fhir-to-bal-lib/pom.xml
native/fhir-to-bal-template/pom.xml
native/health-cli/pom.xml
pom.xml

[Release v2.2.0] Prepare for release

---

ballerina/src/main/resources/health-tool-ballerina/BalTool.toml

Add CDS dependencies to BalToml

---

ballerina/pom.xml
native/cds-bal-template/pom.xml
native/fhir-to-bal-lib/pom.xml
native/fhir-to-bal-template/pom.xml
native/health-cli/pom.xml
pom.xml

[Release v2.2.0] Prepare for next dev cycle

---

native/health-cli/src/main/java/io/ballerina/health/cmd/cds/CdsSubCmd.java
native/health-cli/src/main/java/io/ballerina/health/cmd/core/utils/HealthCmdConstants.java

> $subject
> https://github.com/wso2-enterprise/open-healthcare/issues/1645

Fix config file path empty issue

---

ballerina/pom.xml
native/cds-bal-template/pom.xml
native/fhir-to-bal-lib/pom.xml
native/fhir-to-bal-template/pom.xml
native/health-cli/pom.xml
pom.xml

[Release v2.2.1] Prepare for next dev cycle

---

native/fhir-to-bal-lib/src/main/resources/templates/fhir_resource.vm

> https://github.com/wso2-enterprise/open-healthcare/issues/1664

Improve custom validation message for array constraints 

---

.github/workflows/cd.yml
.github/workflows/ci.yml
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/modelgen/DatatypeContextGenerator.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/modelgen/ResourceContextGenerator.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/utils/GeneratorUtils.java
native/fhir-to-bal-lib/src/main/resources/templates/fhir_resource.vm
native/health-cli/pom.xml
native/health-cli/src/main/resources/tool-config.json

> $Subject.
> Related issue: https://github.com/wso2-enterprise/open-healthcare/issues/1672

Fix issues with extensions fields in generated resource records

---

native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/ToolConstants.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/config/BallerinaPackageGenToolConfig.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/config/PackageConfig.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/modelgen/ResourceContextGenerator.java
native/fhir-to-bal-lib/src/main/java/org/wso2/healthcare/fhir/ballerina/packagegen/tool/templategen/ResourceTemplateGenerator.java
native/health-cli/src/main/java/io/ballerina/health/cmd/fhir/FhirSubCmd.java
native/health-cli/src/main/java/io/ballerina/health/cmd/handler/FhirPackageGenHandler.java
native/health-cli/src/main/resources/ballerina-health.help

> $subject
> Introduced another parameter --profile-dependencies, and users can pass key-value pair of profile URL and Ballerina package.
> https://github.com/wso2-enterprise/open-healthcare/issues/1670

Fix profile dependency resolving issue

---

native/health-cli/src/main/resources/ballerina-health-cds.help

> $subject
> https://github.com/wso2-enterprise/open-healthcare/issues/1667

Improve CDS help text

---

ballerina/pom.xml
native/cds-bal-template/pom.xml
native/fhir-to-bal-lib/pom.xml
native/fhir-to-bal-template/pom.xml
native/health-cli/pom.xml
pom.xml

[Release v2.2.3] Prepare for release

---

ballerina/pom.xml
native/cds-bal-template/pom.xml
native/fhir-to-bal-lib/pom.xml
native/fhir-to-bal-template/pom.xml
native/health-cli/pom.xml
pom.xml

[Release v2.2.3] Prepare for next dev cycle

---

.github/workflows/cd.yml
.github/workflows/ci.yml
ballerina/src/main/resources/health-tool-ballerina/BalTool.toml
native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/BallerinaProjectConstants.java
native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/generator/BallerinaProjectGenerator.java
native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/generator/ComponentYamlGenerator.java
native/fhir-to-bal-template/src/main/java/org/wso2/healthcare/fhir/codegen/ballerina/project/tool/generator/OasGenerator.java
native/fhir-to-bal-template/src/main/resources/template/componentYaml.vm
pom.xml

> $Subject.
> Related issues: 
> - https://github.com/wso2-enterprise/open-healthcare/issues/1676
> - https://github.com/wso2-enterprise/open-healthcare/issues/1577

OAS gen support and component yaml inclusion for FHIR templates

---

.github/workflows/cd.yml

Add fix for CD workflow version update step

---

ballerina/pom.xml
native/cds-bal-template/pom.xml
native/fhir-to-bal-lib/pom.xml
native/fhir-to-bal-template/pom.xml
native/health-cli/pom.xml
pom.xml

[Release v2.2.5] Prepare for release

---

ballerina/pom.xml
native/cds-bal-template/pom.xml
native/fhir-to-bal-lib/pom.xml
native/fhir-to-bal-template/pom.xml
native/health-cli/pom.xml
pom.xml

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

[release-3.0.0]Prepare for next development cycle

---

ballerina/pom.xml
native/cds-bal-template/pom.xml
native/fhir-to-bal-lib/pom.xml
native/fhir-to-bal-template/pom.xml
native/health-cli/pom.xml
pom.xml

[Release Health Tool 3.2.0] Prepare for release
